name: npm-publish

on:
  release:
    types: [created]

jobs:
  publish_to_npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sarina'
      - run: RELEASE_TAG=$(git tag --sort=committerdate | tail -1) && yarn version --force --no-git-tag-version --no-commit-hooks --new-version $RELEASE_TAG
      - run: yarn install
      - run: yarn build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}